apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp1
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp1
    spec:
      containers:
      - image: ngnix:latest
        name: ngnix
        resources: {}
status: {}
